[project]
name = "building-block-rq1"
version = "1.6.0"
description = "Add your description here"
authors = [{ name = "Nguyen Duc Toan", email = "nto7hc@bosch.com" }]
dependencies = [
    "requests>=2.26.0",
    "aiohttp>=3.8.0",
    "pydantic>=2.7.1",
    "rich>=13.7.1",
    "deprecated>=1.2.14",
]
readme = "README.md"
requires-python = ">= 3.9"

[project.optional-dependencies]
ssl = ["requests<=2.29.0"]
test = [
    "pytest>=8.2.1",
    "coverage>=7.5.1",
    "pytest-xdist>=3.6.1",
    "ruff>=0.4.4",
    "pytest-asyncio>=1.0.0",
]
doc = ["sphinx>=7.3.7", "sphinx-rtd-theme>=2.0.0", "autodoc-pydantic>=2.2.0"]
dev = [
    "pyright>=1.1.363",
    "ruff>=0.4.4",
    "ruff-lsp>=0.0.53",
    "rdflib>=7.0.0",
    "jinja2>=3.1.4",
    "pytest>=8.2.1",
    "coverage>=7.5.1",
    "pytest-xdist>=3.6.1",
    "sphinx>=7.3.7",
    "sphinx-rtd-theme>=2.0.0",
    "autodoc-pydantic>=2.2.0",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.metadata]
allow-direct-references = true

[tool.hatch.build.targets.wheel]
packages = ["src/rq1"]

[tool.ruff]
# eclude linting anf formatting auto-generated files
exclude = ["src/rq1/*.py"]

[tool.coverage.report]
omit = ["examples/*"]
exclude_also = ["def __repr__", 'def create_\w+_changeset']

[tool.pytest.ini_options]
testpaths = ["tests", "examples"]
python_classes = []
python_files = ['tests/test*.py', 'examples/*.py']
python_functions = ['test*', 'example*']
filterwarnings = [
    'ignore::urllib3.exceptions.InsecureRequestWarning',
    'ignore::pytest.PytestUnraisableExceptionWarning',
]
